### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by rexkyo** [loadimpact/homebrew-k6#1]
Hi,

i have a install error

==> ./node_modules/.bin/ember build -prod
Last 15 lines from /Users/rexkyo/Library/Logs/Homebrew/k6/04.ember:
WARNING: Node v8.0.0 has currently not been tested against Ember CLI and may result in unexpected behaviour.
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
Missing template processor
Error: Missing template processor
    at module.exports.preprocessTemplates (/private/tmp/k6-20170605-69938-82zg9c/src/github.com/loadimpact/k6/web/node_modules/ember-cli-preprocess-registry/preprocessors.js:162:11)
    at EmberApp._processedTemplatesTree (/private/tmp/k6-20170605-69938-82zg9c/src/github.com/loadimpact/k6/web/node_modules/ember-cli/lib/broccoli/ember-app.js:833:48)
    at EmberApp.appAndDependencies (/private/tmp/k6-20170605-69938-82zg9c/src/github.com/loadimpact/k6/web/node_modules/ember-cli/lib/broccoli/ember-app.js:1060:24)
    at EmberApp.javascript (/private/tmp/k6-20170605-69938-82zg9c/src/github.com/loadimpact/k6/web/node_modules/ember-cli/lib/broccoli/ember-app.js:1199:34)
    at EmberApp.toArray (/private/tmp/k6-20170605-69938-82zg9c/src/github.com/loadimpact/k6/web/node_modules/ember-cli/lib/broccoli/ember-app.js:1604:10)
    at EmberApp.toTree (/private/tmp/k6-20170605-69938-82zg9c/src/github.com/loadimpact/k6/web/node_modules/ember-cli/lib/broccoli/ember-app.js:1626:30)
    at module.exports (/private/tmp/k6-20170605-69938-82zg9c/src/github.com/loadimpact/k6/web/ember-cli-build.js:41:14)
    at Class.setupBroccoliBuilder (/private/tmp/k6-20170605-69938-82zg9c/src/github.com/loadimpact/k6/web/node_modules/ember-cli/lib/models/builder.js:74:19)
    at Class.init (/private/tmp/k6-20170605-69938-82zg9c/src/github.com/loadimpact/k6/web/node_modules/ember-cli/lib/models/builder.js:54:10)
    at Class.superWrapper [as init] (/private/tmp/k6-20170605-69938-82zg9c/src/github.com/loadimpact/k6/web/node_modules/core-object/lib/assign-properties.js:32:18)

**Comment by mjb2kmn** [comment]
I came to report the same error. Here is my `brew config`

```
HOMEBREW_VERSION: 1.2.2
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 54e01d76db34a3a649c79b189873bfd0a52dbc9f
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 5d7518e378e660d1d2b3579f955039ebb12ffc21
Core tap last commit: 60 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
Clang: 8.1 build 802
Git: 2.12.2 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.4.1_1/bin/ruby
Java: 1.8.0_31, 1.7.0_75
macOS: 10.12.4-x86_64
Xcode: N/A
CLT: 8.3.2.0.1.1492020469
X11: 2.7.7 => /opt/X11
```

**Comment by s2pla** [comment]
not able to install k6 on mac
when i do 'brew install k6' getting:

npm
install
ember-cli
bower
--verbose

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/loadimpact/homebrew-k6/issues

**Comment by rexkyo** [comment]
Just re-try to install after you have been able to use :)

**Comment by mjb2kmn** [comment]
I'm not entirely sure what that sentence means ;), but I tried to install again and confirm it does work now.
